---
permalink: online-help/concept-all-workloads.html 
sidebar: sidebar 
keywords: workloads,workloads 
summary: All工作負載檢視會顯示資料中心叢集上所有可用工作負載的清單。 
---
= 所有工作負載
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
All工作負載檢視會顯示資料中心叢集上所有可用工作負載的清單。

All工作負載檢視會列出與ONTAP Unified Manager所管理的各個叢集相關的儲存工作負載。此頁面也可讓您將儲存效率原則和效能服務層級指派給儲存工作負載。

當您將叢集新增至Unified Manager時、系統會自動探索並顯示每個叢集上的儲存工作負載、FlexGroup 但不包括下列項目：

Unified Manager只會在儲存工作負載上開始執行I/O作業之後、才開始分析工作負載以提出建議（建議的效能服務層級）。對於未執行I/O作業的新發現儲存工作負載、狀態為「waiting for I/O（正在等待I/O）」。在儲存工作負載上開始執行I/O作業之後、Unified Manager會開始分析、工作負載狀態會變更為「Learning ...」。完成分析後（從I/O作業開始算起24小時內）、系統會針對儲存工作負載顯示建議的效能服務層級。

使用*工作負載*>*所有工作負載*選項、您可以執行多項工作：

* 新增或配置儲存工作負載
* 檢視及篩選工作負載清單
* 將效能服務層級指派給個別的儲存工作負載
* 將系統建議的效能服務層級指派給所有未指派的工作負載
* 指派儲存效率原則給儲存工作負載




== 新增或配置儲存工作負載

您可以新增或配置儲存工作負載至支援的LUN（同時支援iSCSI和FCP傳輸協定）、NFS檔案共用和SMB共用。



== 檢視及篩選工作負載

在「All Workload」（所有工作負載）畫面上、您可以檢視資料中心中的所有工作負載、或根據指派給它們的Performance Service層級或工作負載名稱來搜尋特定的儲存工作負載。您可以使用篩選圖示輸入搜尋的特定條件。您可以依不同的篩選條件（例如主機叢集或儲存VM）進行搜尋。如果您選取*容量總計*選項、就可以依工作負載的總容量進行搜尋。傳回的工作負載數量可能會因輸入的確切篩選條件而有所不同、因為容量是以位元組層級進行比較。畫面會顯示工作負載的儲存資訊、例如主機叢集和儲存VM、以及效能服務層級和儲存效率原則（如果有）。

此頁面也可讓您檢視工作負載的效能詳細資料。您可以按一下「*選擇/訂單欄*」按鈕、然後選取要檢視的特定欄、以檢視工作負載的IOPS、容量和延遲等詳細資訊。「效能檢視」欄會顯示工作負載的平均和尖峰IOPS、您可以按一下工作負載分析器圖示來檢視詳細的IOPS分析。「IOPS分析」快顯視窗上的「分析工作負載*」按鈕會帶您前往「工作負載分析」頁面、您可在其中選取時間範圍、並檢視所選工作負載的延遲、處理量和容量趨勢。如需工作負載分析器的詳細資訊、請參閱_使用工作負載分析器疑難排解工作負載_

link:concept-troubleshooting-workloads-using-the-workload-analyzer.adoc["使用工作負載分析器疑難排解工作負載"]



== 指派效能服務層級給儲存工作負載

您可以將效能服務層級指派給單一或多個儲存工作負載。使用畫面上的不同導覽、您可以為工作負載指派特定或系統建議的效能服務層級。



== 將系統建議的效能服務層級指派給所有未指派的工作負載

您可以將效能服務層級指派給資料中心中未指派任何PSL的所有儲存工作負載、前提是工作負載必須具備系統建議的效能服務層級。此功能對於沒有任何系統建議的效能服務層級可用的工作負載而言、並不有效。若要使用此功能、請按一下*指派系統建議的PSL*按鈕。系統會內部評估未指派儲存工作負載的適當效能服務層級、並顯示可指派效能服務層級的工作負載總數。



== 指派儲存效率原則給儲存工作負載

您可以將儲存效率原則指派給單一或多個儲存工作負載。透過畫面上的不同導覽、您可以將特定的儲存效率原則指派給儲存工作負載。



== 將效能服務層級和儲存效率原則指派在一起

您可以將「效能服務層級」和「儲存效率原則」指派給單一工作負載。請遵循下列步驟：

. 按一下該列的編輯圖示、然後按一下*編輯*。
+
「*指派的效能服務層級*」和「*儲存效率原則*」欄位已啟用。

. 選取所需的效能服務層級和儲存效率原則。
. 按一下核取圖示以套用變更。




== 分析工作負載的效能與容量條件

您可以按一下「*效能檢視*」欄中的橫條圖圖示、檢視工作負載的效能資訊、以協助疑難排解。若要在「工作負載分析」頁面上檢視效能與容量圖表以分析物件、請按一下「*分析工作負載*」按鈕。
