---
permalink: online-help/concept-managing-storage-efficiency-policies.html 
sidebar: sidebar 
keywords: add 
summary: 儲存效率原則（SEP）可讓您定義工作負載的儲存效率特性。您可以在最初建立工作負載時、或之後編輯工作負載、將儲存效率原則指派給工作負載。 
---
= 管理儲存效率原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儲存效率原則（SEP）可讓您定義工作負載的儲存效率特性。您可以在最初建立工作負載時、或之後編輯工作負載、將儲存效率原則指派給工作負載。

儲存效率包括使用精簡配置、重複資料刪除及資料壓縮等技術、以提高儲存使用率並降低儲存成本。在建立儲存效率原則的同時、您可以個別或一起使用這些節省空間的技術、以達到最大儲存效率。當您將原則與儲存工作負載建立關聯時、系統會將指定的原則設定指派給這些原則。Unified Manager可讓您指派系統定義和使用者定義的儲存效率原則、以最佳化資料中心的儲存資源。

Unified Manager提供兩種系統定義的儲存效率原則：高與低。這些DDP適用於資料中心的大部分儲存工作負載、不過、如果系統定義的DDP不符合您的需求、您可以自行建立原則。

您無法修改系統定義或目前指派給工作負載的儲存效率原則。您無法刪除指派給工作負載的儲存效率原則、或是唯一可用的儲存效率原則。

「儲存效率原則」頁面會列出可用的儲存效率原則、並可讓您新增、編輯及刪除自訂的DDP。此頁面顯示下列資訊：

[cols="1a,1a"]
|===
| 欄位 | 說明 


 a| 
名稱
 a| 
儲存效率原則名稱。



 a| 
類型
 a| 
原則是由系統定義還是由使用者定義。



 a| 
空間保留
 a| 
磁碟區是精簡配置或完整配置。



 a| 
重複資料刪除
 a| 
是否在磁碟區上啟用重複資料刪除：

* `Inline`：在捲上寫入重複資料刪除功能時會發生
* `Background`：重複資料刪除是在背景執行
* `Disable`：已停用磁碟區上的重複資料刪除功能




 a| 
壓縮
 a| 
是否在Volume上啟用資料壓縮：

* `Inline`：在捲上寫入資料時會進行資料壓縮
* `Background`：資料壓縮會在背景中進行
* `Disable`：已停用磁碟區上的資料壓縮功能




 a| 
工作負載
 a| 
已指派儲存效率原則的儲存工作負載數量

|===


== 建立自訂儲存效率原則的準則

如果現有的儲存效率原則不符合儲存工作負載的原則需求、您可以建立自訂的儲存效率原則。不過、建議您嘗試針對儲存工作負載使用系統定義的儲存效率原則、並視需要僅建立自訂的儲存效率原則。
