---
permalink: online-help/concept-monitoring-vms.html 
sidebar: sidebar 
keywords: virtual machines 
summary: 對於虛擬機器（VM）應用程式的任何延遲問題、您可能需要監控VM、以分析並疑難排解原因。 
---
= 監控虛擬機器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
對於虛擬機器（VM）應用程式的任何延遲問題、您可能需要監控VM、以分析並疑難排解原因。

利用NetApp功能、您可以檢視VM應用程式的詳細拓撲、其中會顯示VM相關的元件、例如VM主機或與其相連的資料存放區Active IQ Unified Manager 。拓撲檢視會依下列順序、以其特定層級顯示基礎元件：*虛擬磁碟*>* VM*>*主機*>*網路*>*資料存放區*>* VMDK *。

[NOTE]
====
若要檢視資料存放區（儲存層）的度量、必須ONTAP 將父級的支援叢集新增至Unified Manager、而且必須完成叢集的探索（輪詢或收集度量）。

====
您可以從拓撲層面判斷I/O路徑和元件層級延遲、並識別儲存設備是否是造成效能問題的原因。拓撲的摘要檢視會顯示I/O路徑、並強調有IOPS和延遲問題的元件、供您決定疑難排解步驟。您也可以展開拓撲檢視、分別描述每個元件以及該元件的延遲。您可以選取元件、以決定在各層中反白顯示的I/O路徑。



== vCenter資料收集排程

針對輪詢vCenter組態資料、Unified Manager會依照收集叢集組態資料的相同排程進行。如需vCenter組態與效能資料收集排程的相關資訊、請參閱「叢集組態與效能資料收集活動」。

vCenter會收集20秒的即時效能資料樣本、並將其彙整至5分鐘的樣本。Unified Manager的效能資料收集排程是根據vCenter伺服器的預設設定而定。Unified Manager會處理從vCenter取得的5分鐘樣本、並計算虛擬磁碟、VM和主機的每小時IOPS和延遲平均值。對於資料存放區、Unified Manager會根據ONTAP 從NetApp取得的樣本、計算每小時的IOPS平均值和延遲時間。這些值可在每小時的最上方取得。新增vCenter之後、效能指標將無法立即使用、而且只有在下一個小時開始時才可使用。效能資料輪詢是從完成組態資料收集週期開始。



== 檢視摘要拓撲

透過在摘要拓撲中檢視VM來判斷效能問題

. 轉至* VMware*>*虛擬機器*。
. 在搜尋方塊中輸入VM名稱、即可搜尋VM。您也可以按一下「*篩選*」按鈕、根據特定條件篩選搜尋結果。不過、如果找不到VM、請確定已新增並探索對應的vCenter。
+
[NOTE]
====
vCenter伺服器允許使用特殊字元（例如%、&、*、$、#、@、！、\、/、：、*、？、"、"、<、>、在vSphere實體名稱中、例如VM、叢集、資料存放區、資料夾、或檔案。VMware vCenter Server和ESX/ESXi Server不會轉義顯示名稱中使用的特殊字元。不過、在Unified Manager中處理名稱時、其顯示方式會有所不同。例如、名稱為的VM `%$VC_AIQUM_clone_191124%` 在vCenter伺服器中顯示為 `%25$VC_AIQUM_clone_191124%25` 統一化管理程式：當您查詢名稱中有特殊字元的VM時、必須記下此問題。

====
. 檢查VM的狀態。VM狀態會從vCenter擷取。下列狀態可供使用。如需這些狀態的詳細資訊、請參閱VMware文件。
+
** 正常
** 警告
** 警示
** 未監控
** 不明


. 按一下VM旁的向下箭頭、即可查看整個運算、網路和儲存層元件拓撲的摘要檢視。出現延遲問題的節點會反白顯示。摘要檢視會顯示元件的最短延遲時間。例如、如果VM有多個虛擬磁碟、此檢視會顯示所有虛擬磁碟之間延遲最短的虛擬磁碟。
. 若要分析資料存放區一段時間內的延遲和處理量、請按一下資料存放區物件圖示頂端的*工作負載分析器*按鈕。您可以前往「工作負載分析」頁面、選取時間範圍並檢視資料存放區的效能圖表。如需工作負載分析器的詳細資訊、請參閱_使用工作負載分析器疑難排解工作負載_。
+
link:concept-troubleshooting-workloads-using-the-workload-analyzer.adoc["使用工作負載分析器疑難排解工作負載"]





== 檢視擴充拓撲

您可以檢視VM的擴充拓撲、分別深入各個元件。

. 在摘要拓撲檢視中、按一下*展開拓撲*。您可以分別查看每個元件的詳細拓撲、以及每個物件的延遲數。如果類別中有多個節點（例如資料存放區或VMDK中有多個節點）、則延遲時間最短的節點會以紅色強調顯示。
. 若要檢查特定物件的IO路徑、請按一下該物件以查看IO路徑和對應。例如、若要查看虛擬磁碟的對應關係、請按一下虛擬磁碟、以檢視其反白顯示的對應關係至各自的VMDK。如果這些元件的效能延遲、您可以從ONTAP VMware收集更多資料、並疑難排解問題。
+
[NOTE]
====
不會報告VMDK的度量。在拓撲中、只會顯示VMDK名稱、而不會顯示度量。

====

