---
permalink: online-help/task-viewing-and-adding-vcenter-servers.html 
sidebar: sidebar 
keywords: vCenter server 
summary: 若要檢視及疑難排解虛擬機器的效能（VMs）、必須在Active IQ Unified Manager 您的VMware執行個體上新增相關的vCenter。 
---
= 檢視及新增vCenter伺服器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要檢視及疑難排解虛擬機器（VM）的效能、必須在Active IQ Unified Manager 您的VMware執行個體上新增相關的vCenter。



== 開始之前

在新增或檢視vCenter之前、請確認下列事項：

* 您知道vCenter名稱。
* vCenter可供成功探索。
* 新增vCenter時、您知道IP位址並擁有認證資料。認證資料必須是vCenter管理員或擁有vCenter唯讀存取權的root使用者。
* 您要新增的vCenter會執行vSphere 6.5或更新版本。
* vCenter伺服器中的資料收集設定在5分鐘間隔內設為層級3
* vCenter中的延遲值以毫秒為單位進行設定、而非以微秒為單位、以便成功計算延遲值。
* vCenter時間屬於vCenter的時區。




== 關於這項工作

對於每個新增和探索的vCenter、Unified Manager都會收集組態資料、例如vCenter和ESXi伺服器詳細資料、ONTAP 不完整的對應、資料存放區詳細資料、以及託管的VM數量。它進一步收集元件的效能指標。



== 步驟

. 移至* VMware*>* vCenter/*、然後檢查清單上是否有vCenter可供使用。
+
[NOTE]
====
如果vCenter無法使用、您必須新增vCenter。

====
+
.. 按一下「 * 新增 * 」。
.. 為vCenter新增正確的IP位址、並確保裝置可連線。
.. 新增具有vCenter唯讀存取權的系統管理員或root使用者的使用者名稱和密碼。
.. 如果您使用預設以外的任何連接埠、請新增自訂連接埠號碼 `443`。
.. 按一下「 * 儲存 * 」。成功探索後、系統會顯示伺服器憑證供您接受。
+
當您接受憑證時、vCenter會新增至可用vCenter清單。新增裝置並不會導致相關VM的資料收集、而且會以排定的時間間隔進行收集。



. 如果您的vCenter可在* vCenters *頁面上使用、請檢查其狀態。將滑鼠游標移到「*狀態*」欄位上、會顯示vCenter是否如預期般執行、或是出現警告或錯誤。
+
[NOTE]
====
新增vCenter可讓您檢視下列狀態。不過、新增vCenter之後、相對應VM的效能和延遲資料可能需要一小時才能準確反映出來。

====
+
** 綠色：正常、表示vCenter已被探索、效能指標已成功收集
** 黃色：警告（例如、vCenter伺服器的統計資料層級尚未設定為3或以上、無法取得每個物件的統計資料）
** 橘色：錯誤（指出任何內部錯誤、例如例外、組態資料收集失敗或vCenter無法連線）您可以按一下欄顯示圖示（*顯示/隱藏*）、檢視vCenter狀態的狀態訊息、並疑難排解問題。


. 如果vCenter無法連線或認證資料已變更、請編輯vCenter詳細資料。選取vCenter、然後按一下*編輯*。
. 在「*編輯VMware vCenter Server*」頁面上進行必要的變更。
. 按一下「 * 儲存 * 」。
+
成功探索之後、vCenter的狀態就會變更。


