---
permalink: online-help/task-provisioning-fileshares.html 
sidebar: sidebar 
keywords:  
summary: 「Provision Workload」（資源配置工作負載）頁面可讓您針對現有的叢集和儲存虛擬機器（儲存VM）建立LUN（同時支援iSCSI和FCP傳輸協定）或檔案共用（支援CIFS/SMB和NFS傳輸協定）。 
---
= 資源配置工作負載
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「Provision Workload」（資源配置工作負載）頁面可讓您針對現有的叢集和儲存虛擬機器（儲存VM）、建立LUN（同時支援iSCSI和FCP傳輸協定）或檔案共用（支援CIFS/SMB和NFS傳輸協定）。



== 開始之前

* 至少應在儲存VM上啟用其中一個SMB、NFS、iSCSI和FCP服務、或是所有服務。如果您要建立LUN、則必須同時啟用iSCSI和FCP。
* 若要在工作負載上選取及指派效能服務層級和儲存效率原則、必須先建立原則、才能開始建立工作負載。




== 步驟

. 在「*資源配置工作負載*」頁面上、新增您要建立的工作負載名稱、然後從您要建立工作負載的可用清單中選取叢集。
. 根據您選取的叢集、*儲存VM*欄位會篩選該叢集的可用儲存虛擬機器。從清單中選取所需的儲存VM。
+
根據儲存VM支援的SMB、NFS、iSCSI和FCP服務、NAS和SAN選項會在主機資訊區段中啟用。

. 在「*儲存與最佳化*」區段中、指派儲存容量與效能服務層級、以及選擇性地指派工作負載的儲存效率原則。
+
效能服務層級的規格會套用至工作負載、而儲存效率原則的規格則會在建立工作負載時指派給適用的磁碟區和LUN。

. 如果您要強制執行指派給工作負載的效能服務層級、請選取「*強制效能限制*」核取方塊。將效能服務層級指派給工作負載、可確保建立工作負載的集合體、能夠支援在個別效能服務層級中定義的效能與容量目標。例如、如果指派工作負載為「極致效能」、則要配置工作負載的集合體應具備支援「極致效能」效能服務層級（例如SSD儲存設備）效能與容量目標的能力。
+
[NOTE]
====
除非您選取此核取方塊、否則效能服務層級不會套用至工作負載、儀表板上的工作負載狀態會顯示為未指派。

====
. 如果您要建立SMB和/或NFS檔案共用、請選取* NAS*按鈕。只有在儲存VM已啟用所需服務時、才會啟用此按鈕以供選擇。
+
[NOTE]
====
如果SVM同時啟用SMB和NFS服務、您可以選取*「Share by NFS*」和「* Share by SMB*」按鈕、建立同時支援NFS和SMB傳輸協定的檔案共用。如果您要建立SMB或CIFS共用區、請只選取個別的按鈕。

====
+
.. 對於NFS檔案共用、請指定主機或網路的IP位址、以存取檔案共用磁碟區。您可以為多個主機輸入以逗號分隔的值。
+
在新增主機IP位址時、會執行內部檢查、以將主機詳細資料與SVM配對、並建立該主機的匯出原則、或是在現有原則存在的情況下、重新使用該原則。如果有多個NFS共用是針對同一部主機所建立、則相同主機的可用匯出原則會針對所有檔案共用重複使用符合的規則。當您使用API來配置NFS共用時、可以使用指定個別原則規則或提供特定原則金鑰來重複使用原則的功能。

.. 針對SMB共用區、指定哪些使用者或使用者群組可以存取SMB共用區、並指派所需的權限。針對每個使用者群組、在建立檔案共用期間會產生新的存取控制清單（ACL）。


. 若要建立LUN、請選取* SAN*按鈕。只有在選取的儲存VM已啟用所需服務時、才會啟用此按鈕以供選取。
+
.. 選取主機作業系統。
.. 指定LUN的主機對應。您可以指派現有的啟動器群組（igroup）、或定義新的igroup並對應至LUN、以控制哪些啟動器可以存取LUN。
+

NOTE: 如果您在配置LUN時建立新的igroup、則需要等到下一個探索週期（最多15分鐘）、才能將其用於建立LUN。因此、建議您使用可用igroup清單中現有的igroup。

+
如果您要建立新的igroup、請選取*建立新的啟動器群組*按鈕、然後輸入建立igroup所需的資訊。



. 按一下「 * 儲存 * 」。


工作負載會新增至儲存工作負載清單。
