---
settings:
  name: Active IQ Unified Manager 9.7
  downlevel: true
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '9.7'
    url: "/active-iq-unified-manager-97"
  - version-number: '9.9'
    url: "/active-iq-unified-manager-99"
  - version-number: '9.8'
    url: "/active-iq-unified-manager-98"
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: 產品資訊9.7文件Active IQ Unified Manager
    url: "/index.html"
  - title: 版本資訊
    url: "/release-notes.html"
  - title: 開始使用
    entries:
    - title: VMware vSphere的快速入門安裝
      url: "/install-vapp/qsg-vapp.html"
    - title: Linux快速入門安裝
      url: "/install-linux/qsg-linux.html"
    - title: Windows快速入門安裝
      url: "/install-windows/qsg-windows.html"
  - section: install-vapp
  - section: install-linux
  - section: install-windows
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - section: data-protection
  - section: reporting
  - section: api-automation
  - title: 法律聲明
    url: "/reference-legal-notices.html"
