---
permalink: install-windows/task-changing-the-jboss-password-on-windows.html 
sidebar: sidebar 
keywords:  
summary: 您可以建立新的自訂jboss密碼、以覆寫安裝期間設定的預設密碼。此工作為選用工作、但有些站台可能需要此安全功能、才能覆寫Unified Manager安裝預設設定。此作業也會變更jboss存取MySQL所用的密碼。 
---
= 變更jboss密碼
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以建立新的自訂jboss密碼、以覆寫安裝期間設定的預設密碼。此工作為選用工作、但有些站台可能需要此安全功能、才能覆寫Unified Manager安裝預設設定。此作業也會變更jboss存取MySQL所用的密碼。



== 開始之前

* 您必須擁有安裝Unified Manager的系統的Windows管理員權限。
* 您必須擁有MySQL root使用者的密碼。
* 您必須能夠存取NetApp提供的 `password.bat` 指令碼 `\Program Files\NetApp\essentials\bin`。




== 步驟

. 以管理使用者身分登入Unified Manager主機。
. 使用Windows服務主控台停止下列Unified Manager服務：
+
** NetApp Active IQ 收購服務（Ocia-au）
** NetApp Active IQ 產品資料管理伺服器服務（Oncommandsvc）


. 啟動 `password.bat` 開始密碼變更程序的指令碼： `C:\Program Files\NetApp\essentials\bin> password.bat resetJBossPassword`
. 出現提示時、請輸入MySQL root使用者密碼。
. 出現提示時、請輸入目前的jboss使用者密碼。
+
預設密碼為 `D11h1aMu@79%`。

. 出現提示時、請輸入新的jboss使用者密碼、然後再次輸入以供確認。
+
確認訊息會隨著變更而顯示、最後一次會提示您輸入新的jboss使用者密碼。

. 再輸入一次新的jboss使用者密碼。
. 指令碼完成後、請使用Windows服務主控台啟動Unified Manager服務：
+
** NetApp Active IQ 產品資料管理伺服器服務（Oncommandsvc）
** NetApp Active IQ 收購服務（Ocia-au）


. 所有服務啟動後、您就可以登入Unified Manager UI。

